// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeptsColumns holds the columns for the "depts" table.
	DeptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dept_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
		{Name: "ext", Type: field.TypeString, Nullable: true},
	}
	// DeptsTable holds the schema information for the "depts" table.
	DeptsTable = &schema.Table{
		Name:       "depts",
		Columns:    DeptsColumns,
		PrimaryKey: []*schema.Column{DeptsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_code", Type: field.TypeString, Unique: true, Size: 10},
		{Name: "username", Type: field.TypeString, Size: 10},
		{Name: "password", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "default_password", Type: field.TypeString, Size: 50},
		{Name: "is_admin", Type: field.TypeEnum, Nullable: true, Enums: []string{"0", "1"}, Default: "1"},
		{Name: "create_time", Type: field.TypeInt64, Default: 1669382798},
		{Name: "login_time", Type: field.TypeInt64, Nullable: true},
		{Name: "auth_list", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeptsTable,
		UsersTable,
	}
)

func init() {
}
