// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project/ent/dept"
	"project/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeptUpdate is the builder for updating Dept entities.
type DeptUpdate struct {
	config
	hooks    []Hook
	mutation *DeptMutation
}

// Where appends a list predicates to the DeptUpdate builder.
func (du *DeptUpdate) Where(ps ...predicate.Dept) *DeptUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetDeptId sets the "deptId" field.
func (du *DeptUpdate) SetDeptId(s string) *DeptUpdate {
	du.mutation.SetDeptId(s)
	return du
}

// SetName sets the "name" field.
func (du *DeptUpdate) SetName(s string) *DeptUpdate {
	du.mutation.SetName(s)
	return du
}

// SetParentId sets the "parentId" field.
func (du *DeptUpdate) SetParentId(s string) *DeptUpdate {
	du.mutation.SetParentId(s)
	return du
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (du *DeptUpdate) SetNillableParentId(s *string) *DeptUpdate {
	if s != nil {
		du.SetParentId(*s)
	}
	return du
}

// ClearParentId clears the value of the "parentId" field.
func (du *DeptUpdate) ClearParentId() *DeptUpdate {
	du.mutation.ClearParentId()
	return du
}

// SetExt sets the "ext" field.
func (du *DeptUpdate) SetExt(s string) *DeptUpdate {
	du.mutation.SetExt(s)
	return du
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (du *DeptUpdate) SetNillableExt(s *string) *DeptUpdate {
	if s != nil {
		du.SetExt(*s)
	}
	return du
}

// ClearExt clears the value of the "ext" field.
func (du *DeptUpdate) ClearExt() *DeptUpdate {
	du.mutation.ClearExt()
	return du
}

// Mutation returns the DeptMutation object of the builder.
func (du *DeptUpdate) Mutation() *DeptMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DeptUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		if err = du.check(); err != nil {
			return 0, err
		}
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeptMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = du.check(); err != nil {
				return 0, err
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DeptUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DeptUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DeptUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DeptUpdate) check() error {
	if v, ok := du.mutation.DeptId(); ok {
		if err := dept.DeptIdValidator(v); err != nil {
			return &ValidationError{Name: "deptId", err: fmt.Errorf(`ent: validator failed for field "Dept.deptId": %w`, err)}
		}
	}
	if v, ok := du.mutation.Name(); ok {
		if err := dept.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Dept.name": %w`, err)}
		}
	}
	return nil
}

func (du *DeptUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dept.Table,
			Columns: dept.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dept.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.DeptId(); ok {
		_spec.SetField(dept.FieldDeptId, field.TypeString, value)
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(dept.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.ParentId(); ok {
		_spec.SetField(dept.FieldParentId, field.TypeString, value)
	}
	if du.mutation.ParentIdCleared() {
		_spec.ClearField(dept.FieldParentId, field.TypeString)
	}
	if value, ok := du.mutation.Ext(); ok {
		_spec.SetField(dept.FieldExt, field.TypeString, value)
	}
	if du.mutation.ExtCleared() {
		_spec.ClearField(dept.FieldExt, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dept.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// DeptUpdateOne is the builder for updating a single Dept entity.
type DeptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeptMutation
}

// SetDeptId sets the "deptId" field.
func (duo *DeptUpdateOne) SetDeptId(s string) *DeptUpdateOne {
	duo.mutation.SetDeptId(s)
	return duo
}

// SetName sets the "name" field.
func (duo *DeptUpdateOne) SetName(s string) *DeptUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetParentId sets the "parentId" field.
func (duo *DeptUpdateOne) SetParentId(s string) *DeptUpdateOne {
	duo.mutation.SetParentId(s)
	return duo
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (duo *DeptUpdateOne) SetNillableParentId(s *string) *DeptUpdateOne {
	if s != nil {
		duo.SetParentId(*s)
	}
	return duo
}

// ClearParentId clears the value of the "parentId" field.
func (duo *DeptUpdateOne) ClearParentId() *DeptUpdateOne {
	duo.mutation.ClearParentId()
	return duo
}

// SetExt sets the "ext" field.
func (duo *DeptUpdateOne) SetExt(s string) *DeptUpdateOne {
	duo.mutation.SetExt(s)
	return duo
}

// SetNillableExt sets the "ext" field if the given value is not nil.
func (duo *DeptUpdateOne) SetNillableExt(s *string) *DeptUpdateOne {
	if s != nil {
		duo.SetExt(*s)
	}
	return duo
}

// ClearExt clears the value of the "ext" field.
func (duo *DeptUpdateOne) ClearExt() *DeptUpdateOne {
	duo.mutation.ClearExt()
	return duo
}

// Mutation returns the DeptMutation object of the builder.
func (duo *DeptUpdateOne) Mutation() *DeptMutation {
	return duo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DeptUpdateOne) Select(field string, fields ...string) *DeptUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Dept entity.
func (duo *DeptUpdateOne) Save(ctx context.Context) (*Dept, error) {
	var (
		err  error
		node *Dept
	)
	if len(duo.hooks) == 0 {
		if err = duo.check(); err != nil {
			return nil, err
		}
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeptMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = duo.check(); err != nil {
				return nil, err
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, duo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Dept)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DeptMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DeptUpdateOne) SaveX(ctx context.Context) *Dept {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DeptUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DeptUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DeptUpdateOne) check() error {
	if v, ok := duo.mutation.DeptId(); ok {
		if err := dept.DeptIdValidator(v); err != nil {
			return &ValidationError{Name: "deptId", err: fmt.Errorf(`ent: validator failed for field "Dept.deptId": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Name(); ok {
		if err := dept.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Dept.name": %w`, err)}
		}
	}
	return nil
}

func (duo *DeptUpdateOne) sqlSave(ctx context.Context) (_node *Dept, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dept.Table,
			Columns: dept.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dept.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dept.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dept.FieldID)
		for _, f := range fields {
			if !dept.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dept.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.DeptId(); ok {
		_spec.SetField(dept.FieldDeptId, field.TypeString, value)
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(dept.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.ParentId(); ok {
		_spec.SetField(dept.FieldParentId, field.TypeString, value)
	}
	if duo.mutation.ParentIdCleared() {
		_spec.ClearField(dept.FieldParentId, field.TypeString)
	}
	if value, ok := duo.mutation.Ext(); ok {
		_spec.SetField(dept.FieldExt, field.TypeString, value)
	}
	if duo.mutation.ExtCleared() {
		_spec.ClearField(dept.FieldExt, field.TypeString)
	}
	_node = &Dept{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dept.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
