// Code generated by ent, DO NOT EDIT.

package dept

const (
	// Label holds the string label denoting the dept type in the database.
	Label = "dept"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeptId holds the string denoting the deptid field in the database.
	FieldDeptId = "dept_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldParentId holds the string denoting the parentid field in the database.
	FieldParentId = "parent_id"
	// FieldExt holds the string denoting the ext field in the database.
	FieldExt = "ext"
	// Table holds the table name of the dept in the database.
	Table = "depts"
)

// Columns holds all SQL columns for dept fields.
var Columns = []string{
	FieldID,
	FieldDeptId,
	FieldName,
	FieldParentId,
	FieldExt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DeptIdValidator is a validator for the "deptId" field. It is called by the builders before save.
	DeptIdValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
